
version: '3.8'
services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    
  sisbanco-kernel-db:
    image: postgres:15
    container_name: sisbanco-kernel-db
    restart: always    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sisbanco-kernel
    ports:
      - 5433:5432
    volumes:
      - sisbanco_kernel_data:/var/lib/postgresql/data  

  sisbanco-transacoes-db:
    image: mongo
    container_name: sisbanco-transacoes-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=sisbanco-transacoes
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - sisbanco_transacoes_data:/data/db  

  sisbanco-transacoes-cache-db:
    image: redis
    container_name: sisbanco-transacoes-cache-db
    restart: always    
    command: redis-server --save 20 1 --loglevel warning --requirePass 123
    ports:
      - 6379:6379
    volumes:
      - sisbanco_transacoes_cache_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - 8081:8080
    command: [start-dev]
    depends_on:
      - keycloak-db

volumes:
  keycloak_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local

  sisbanco_kernel_data:
    driver: local
  sisbanco_transacoes_data:
    driver: local
  sisbanco_transacoes_cache_data:
    driver: local