
version: '3.8'
services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data
    
  sisbanco-kernel-db:
    image: postgres:15
    container_name: sisbanco-kernel-db
    restart: always    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sisbanco-kernel
    ports:
      - 5433:5432
    volumes:
      - pgdata_sisbanco_kernel:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - 8081:8080
    depends_on:
      - keycloak-db

volumes:
  pgdata_sisbanco_kernel:
    driver: local
  pgdata_keycloak:
    driver: local