
version: '3.8'
services:
  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    
  sisbanco-kernel-db:
    image: postgres:15-alpine
    container_name: sisbanco-kernel-db
    restart: always    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sisbanco-kernel
    ports:
      - 5433:5432
    volumes:
      - sisbanco_kernel_data:/var/lib/postgresql/data

  sisbanco-historico-db:
    image: mongo:7
    container_name: sisbanco-historico-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=sisbanco-historico
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - sisbanco_historico_data:/data/db

  sisbanco-cache-db:
    image: redis:5.0.3-alpine
    container_name: sisbanco-cache-db
    restart: always    
    command: redis-server --save 60 1000 --loglevel debug --requirePass 123
    ports:
      - 6379:6379
    volumes:
      - sisbanco_cache_data:/data    

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_NODENAME=rabbit@rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
      - rabbitmq_conf:/etc/rabbitmq

  keycloak:
    #image: quay.io/keycloak/keycloak:23.0.1
    build: 
      context: ./build/
      dockerfile: keycloak-Dockerfile

    container_name: keycloak
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak?user=postgres&password=postgres&ssl=false
    ports:
      - 8443:8443
    command: ["start", "--https-port=8443", "--hostname=localhost", "--https-key-store-file=/opt/keycloak/conf/keycloak.keystore", "--https-key-store-password=123456"]
    depends_on:
      - keycloak-db

  sisbanco-eureka:
    build: ./sisbanco-eureka/
    container_name: sisbanco-eureka
    restart: always
    environment:
      SERVER_PORT: 8761    
    ports:
      - 8761:8761

  sisbanco-auth:
    build: ./sisbanco-auth/
    container_name: sisbanco-auth
    restart: always
    environment:
      EUREKA_URL: http://sisbanco-eureka:8761/eureka
      KEYCLOAK_SERVER_URL: https://keycloak:8443
      KEYCLOAK_ADMIN_REALM: master
      KEYCLOAK_ADMIN_CLIENT_ID: admin-cli
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_APP_REALM: sisbanco
      KEYCLOAK_APP_CLIENT_ID: sisbanco-app
      KEYCLOAK_APP_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm9Zcq/6Pq7BLuLsn6b7X0HYl/paFeC6qHr65y3FOoc7bYucPa2RcWVKazjVuRWOLZ9N6ppw9CNcLCgIyZ1ctDOzIRLGj2WbypxJ2lsEImVj6dQMSCRLhbuHrRVHSCguc7NqXThME/U+VwIL10duLoqmvUFhESZwDlXZr+CyGzOPGsSGzlmvjdV4GQlQfLrQKUiQy+gKascdpbTOVsojb+7iE6bLFc66KSo2jCmkYt9zSpSFIxGd62mAOE5Q0CPU1wmS//mI5v4Ep8biPNtfFnK5L9nV2bkicl9r0XMWgp6cQ4uErTU5j/atCEtRNR9qicNSxz/xn0bMYbuhl76RF8QIDAQAB    
      TRUSTSTORE_FILE: /opt/sisbanco/conf/keycloak-trust.keystore
      TRUSTSTORE_PASSWORD: 654321
    depends_on:
      - keycloak
      - sisbanco-eureka    

  sisbanco-kernel:
    build: ./sisbanco-kernel/
    container_name: sisbanco-kernel
    restart: always
    environment:
      EUREKA_URL: http://sisbanco-eureka:8761/eureka 
      SISBANCO_KEYCLOAK_URL: http://sisbanco-gateway:8080/api/auth
      DB_URL: jdbc:postgresql://sisbanco-kernel-db:5432/sisbanco-kernel
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      CACHE_DB_HOST: sisbanco-cache-db
      CACHE_DB_PORT: 6379
      CACHE_DB_PASSWORD: 123
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
      RABBITMQ_TRANSACOES_QUEUE: transacoes-queue
      RABBITMQ_TRANSACOES_EXCHANGE: transacoes-exchange
      RABBITMQ_TRANSACOES_ROUTING_KEY: transacoes-routing-key
      RABBITMQ_VIRTUAL_HOST: /
      GLOBAL_ERRO_LOG_FILE: /var/log/sisbanco/kernel-error.log    
    depends_on:
      - keycloak
      - rabbitmq
      - sisbanco-auth
      - sisbanco-kernel-db
      - sisbanco-cache-db
      
  sisbanco-historico:
    build: ./sisbanco-historico/
    container_name: sisbanco-historico
    restart: always
    environment:
      EUREKA_URL: http://sisbanco-eureka:8761/eureka
      KEYCLOAK_URL: http://sisbanco-gateway:8080/api/auth
      DB_HOST: sisbanco-historico-db
      DB_PORT: 27017
      DB_DATABASE: sisbanco-historico
      DB_USERNAME: admin
      DB_PASSORD: admin
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
      RABBITMQ_QUEUE: transacoes-queue
      GLOBAL_ERRO_LOG_FILE: /var/log/sisbanco/historico-error.log            
    depends_on:
      - sisbanco-eureka
      - sisbanco-auth
      - sisbanco-historico-db
      - rabbitmq

  sisbanco-gateway:
    build: ./sisbanco-gateway/
    container_name: sisbanco-gateway
    restart: always
    environment:      
      EUREKA_URL: http://sisbanco-eureka:8761/eureka
      SERVER_PORT: 8080
    ports:
      - 8080:8080       
    depends_on:
      - sisbanco-eureka
      - sisbanco-auth
      - sisbanco-historico
      - sisbanco-kernel

volumes:
  keycloak_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  rabbitmq_conf:
    driver: local

  sisbanco_kernel_data:
    driver: local
  sisbanco_historico_data:
    driver: local
  sisbanco_cache_data:
    driver: local